############################################################
# Dockerfile to install Phant w/WebUI
############################################################

# Set the base image to Ubuntu
FROM node

# File Author / Maintainer
MAINTAINER Shawn McNaughton

# Update the repository sources list
RUN apt-get update --quiet

############################################################
# Get the package from GitHub
############################################################
# Make the repo
# Set up the spare checkout and remote address
# Pull the files
# Copy the package out 
# Delete the repo
RUN mkdir repo \
    && cd repo \
    && git init \
    && git config core.sparsecheckout true \
    && echo PhantServer/phantconfig-custom.tar.gz >> .git/info/sparse-checkout \
    && git remote add -f origin https://github.com/shawngmc/ServerSelfConfig.git \
    && git pull origin master \
    && cp ./PhantServer/phantconfig-custom.tar.gz ../ \
    && cd .. \
    && rm -Rf repo

############################################################
# Install and prep phant
############################################################
# Install phant
RUN tar -xvf phantconfig-custom.tar.gz \
    && npm install

# Expose default HTTP and telnet connector port.
EXPOSE 8080
EXPOSE 8081

# Auto-start phant
ENTRYPOINT npm start